apiVersion: apps/v1
kind: Deployment
metadata:
  name: glass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glass
  template:
    metadata:
      labels:
        app: glass
    spec:
      serviceAccountName: glass
      terminationGracePeriodSeconds: 20
      containers:
        - name: glass
          image: glass:0.1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: auth
              mountPath: /etc/glass/auth
              readOnly: true
            - name: policy
              mountPath: /etc/glass/policy
              readOnly: true
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "info"
            - name: READINESS_STRICT
              value: "false"
            - name: AUTH_MODE
              value: "bearer"
            - name: AUTH_TOKEN_FILE
              value: /etc/glass/auth/token
            - name: POLICY_FILE
              value: /etc/glass/policy/policy.yaml
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
      volumes:
        - name: auth
          secret:
              secretName: webhook-credentials
              items:
                - key: token
                  path: token
        - name: policy
          configMap:
            name: glass-policy
