apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: glass

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - policy-configmap.yaml
