{{- if .Values.storage.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "glass.fullname" . }}-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size }}
  {{- if .Values.storage.persistence.storageClassName }}
  storageClassName: {{ .Values.storage.persistence.storageClassName }}
  {{- end }}
{{- end -}}

