apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glass.fullname" . }}-auth
  labels:
    external-secrets.io/type: webhook
type: Opaque
stringData:
  token: |
{{ .Values.auth.tokenFileContent | indent 4 }}

